version: '3.8'
services:
    postgres:
        image: postgres:15
        container_name: postgres
        restart: unless-stopped
        ports:
            - '5433:5432'
        environment:
            POSTGRES_DB: uid-db-dev
            POSTGRES_USER: ben
            POSTGRES_PASSWORD: ben1234
        volumes:
            - .docker/data/postgres:/var/lib/postgresql/data
        networks:
            - uid-networks

    redis:
        image: redis:7
        container_name: redis
        restart: unless-stopped
        ports:
            - '6379:6379'
        volumes:
            - .docker/data/redis:/data
        networks:
            - uid-networks

networks:
    uid-networks:
