version: '3.8'
services:
    api:
        container_name: api
        image: benacio/uid-api:latest
        restart: unless-stopped
        env_file:
            - ./.env
        environment:
            NODE_ENV: 'production'
            DATABASE_URL: postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}?schema=${PGDATABASE}&sslmode=prefer
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        networks:
            - uid-networks
        command: sh -c 'yarn prisma migrate dev && yarn start:prod'

networks:
    uid-networks:
